import '../../common.blocks/header/header.js'
import '../../common.blocks/benefit_slider/benefit_slider.js'
import '../../main.less'
import './landing-page.less'
import '../../common.blocks/electro_voice/electro_voice.js'
import '../../common.blocks/dinamic_block/dinamic_block.js'
